/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.springapp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringAppApplication {

    public static void main(final String[] args) {
        SpringApplication.run(SpringAppApplication.class, args);
    }

}
